votes <- read.csv("house-votes-84.csv")
votes
install.packages("arules")
install.packages("arulesViz")
library(arules)
library(arulesViz)
vote<-read.transactions("house-votes-84.csv")
class(vote)
inspect(head(vote))
str(vote)
summary(vote)
itemFrequency(vote)
itemFrequency(vote[,'democrat'])
itemFrequency(vote[,'republican'])
frequentItems <- eclat (vote, parameter = list(supp = 0.1, maxlen = 15))
inspect(frequentItems)
image(vote[1:5])
image(sample(vote,25))
itemFrequencyPlot(vote, lift="FALSE",type="absolute", main="Item Frequency",horiz="TRUE",popCol="black")
itemFrequencyPlot(vote, lift="FALSE",type="relative", main="Item Frequency",horiz="TRUE",popCol="black")
rule <- apriori(vote)
inspect(rule)
rules1 <- apriori (vote, parameter = list(supp = 0.07, conf = 0.5))
rules <- apriori (vote, parameter = list(supp = 0.001, conf = 0.08))
inspect(rules)
summary(rules)
